# Starship Prompt Configuration
# By Patrick Ambrose 

# Schema Reference /////////////////////////////////////////////////////////////
"$schema" = 'https://starship.rs/config-schema.json'

# Prompt Configurations ////////////////////////////////////////////////////////
palette = "patppuccin"
follow_symlinks = false
add_newline = true
continuation_prompt = '[… ](bold mauve)'

format = """\
$username \
[on](overlay2) $os$hostname \
[at](overlay2) $directory \
([on](overlay2) $git_branch )\
[via](overlay2) $shell \
[$fill]() \
$jobs \
$cmd_duration\
$line_break\
$character\
"""

right_format = """"""

# Modules Customizations ///////////////////////////////////////////////////////

[username]
style_user = "bold mauve"
style_root = "bold mauve"
format = "[ $user]($style)"
disabled = false
show_always = true

[os]
format = "[$symbol]($style)"
style = "bold pink"
disabled = false

[os.symbols]
Windows = " "
Macos = " "
Linux = " "
Ubuntu = " "
Debian = " "
Raspbian = " "
Arch = " "
Unknown = " "

[hostname]
ssh_only = false
ssh_symbol = '(SSH)'
style = "bold pink"
format = '[$hostname$ssh_symbol]($style)'
trim_at = '.'
disabled = false

[env_var.STARSHIP_DISTRO]
format = '[$env_value]($style)'
style = "bold pink"
variable = "STARSHIP_DISTRO"
disabled = false

[shell]
format = '[$indicator]($style)'
fish_indicator = 'fish'
bash_indicator = 'bash'
zsh_indicator = 'zsh'
powershell_indicator = 'pwsh'
nu_indicator = 'nush'
unknown_indicator = 'sh..'
style = 'bold blue'
disabled = false

[directory]
truncation_length = 1
truncation_symbol = " "
style = "bold green"
home_symbol = " home"
format = "[$path]($style)"

[character]
success_symbol = "[❯](mauve)"
error_symbol = "[❯](red)"

[fill]
symbol = ' '
style = 'bold overlay2'

[cmd_duration]
min_time = 5000                                     #5000
format = '([took ](overlay2)[$duration](bold red))'

[time]
disabled = true
style = "bold green"
format = '[󱑎 $time]($style)'
time_format = '%R'
utc_time_offset = '+5.5'

[git_branch]
symbol = ""
format = "([$symbol $branch]($style))"
truncation_length = 10
truncation_symbol = "…/"
style = "bold peach"

# Programming Language Configuration (Not Used) ////////////////////////////////

[python]
symbol = " "
style = "bold blue"
format = '[$symbol]($style)'

[golang]
symbol = " "
style = "bold sapphire"
format = '[$symbol]($style)'

[nodejs]
symbol = "󰎙 "
style = "bold green"
format = '[$symbol]($style)'

[bun]
symbol = "󰳯 "
style = "bold rosewater"
format = '[$symbol]($style)'

[rust]
symbol = " "
style = "bold peach"
format = '[$symbol]($style)'

# Custom Catppuccin Mocha Palette //////////////////////////////////////////////

[palettes.patppuccin]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
