# Starship Prompt Configuration

# Schema Reference
"$schema" = 'https://starship.rs/config-schema.json'

# Palette Configuration
palette = "patppuccin"

# Add newline configuration
add_newline = true

# Continuation prompt configuration
continuation_prompt = '[… ](bold mauve)'

# Prompt Configurations

# Left Prompt
format = """\
$username \
[on](overlay2) ${env_var.STARSHIP_DISTRO}$hostname \
[at](overlay2) $directory \
([with](overlay2) $git_branch$git_status)\
[$fill]() \
$cmd_duration\
([using](overlay2) $nodejs$bun$python${custom.py_env}$golang$elixir$rust)\
[in](overlay2) $shell \
$line_break\
$character\
"""

# Right Prompt
right_format = """"""

# Prompt Segments

[username]
style_user = "bold mauve"
style_root = "bold mauve"
format = "[ $user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
ssh_symbol = '(SSH)'
style = "bold pink"
format = '[$hostname$ssh_symbol]($style)'
trim_at = '.home.patrickambrose.com'
disabled = false

[env_var.STARSHIP_DISTRO]
format = '[$env_value]($style)'
style = "bold pink"
variable = "STARSHIP_DISTRO"
disabled = false

[shell]
format = '[$indicator]($style)'
fish_indicator = 'fish'
bash_indicator = 'bash'
zsh_indicator = 'zsh'
powershell_indicator = 'pwsh'
nu_indicator = 'nush'
unknown_indicator = 'sh..'
style = 'bold blue'
disabled = false

[directory]
truncation_length = 1
truncation_symbol = " "
style = "bold green"
home_symbol = " home" 
format = "[$path]($style)"

[character]
success_symbol = "[❯](mauve)"
error_symbol = "[❯](red)"

[status]
style = ''
symbol = '[⦿](fg:#f9e2af)'
success_symbol = '[⦿](fg:#a6e3a1)'
not_executable_symbol = '[⦿](fg:#f9e2af)'
not_found_symbol = '[⦿](fg:#f9e2af)'
sigint_symbol = '[⦿](fg:#89dceb)'
signal_symbol = '[⦿](fg:#89b4fa)'
format = '[$symbol]($style)'
map_symbol = true
disabled = false

[fill]
symbol = ' '
style = 'bold overlay2'

[cmd_duration]
min_time = 5000
format = '([took ](overlay2)[$duration ](bold red))'

[time]
disabled = false
style = "bold green"
format = '[󱑎 $time]($style)'
time_format = '%R'
utc_time_offset = '+5.5'

# Prompt configuratiuons for git and git-related tools

[git_branch]
symbol = ""
format = "([$symbol $branch]($style))"
truncation_length = 10
truncation_symbol = "…/"
style = "bold peach"

[git_status]
format = '( [\[$all_status\] ]($style))'
style = "bold peach"
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇄"
up_to_date = "✔"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"


# Prompt configuration for programming languages

[python]
symbol = " "
style = "bold blue"
version_format = "v${major}.${minor}"
format = '[$symbol$version ]($style)'

[custom.py_env]
detect_files = [ 'pyproject.toml' , 'poetry.lock' ]
detect_folders = [ '.venv' , 'venv' ]
style = "bold blue"
format = '[\[$symbol\] ]($style)'
symbol = "󱐋"

[golang]
symbol = " "
style = "bold sapphire"
version_format = "v${major}.${minor}"
format = '[$symbol]($style)'

[nodejs]
symbol = "󰎙 "
style = "bold green"
format = '[$symbol]($style)'
version_format = "v${major}.${minor}"

[bun]
symbol = "󰳯 "
style = "bold rosewater"
format = '[$symbol$version ]($style)'
version_format = "v${major}.${minor}"

[elixir]
symbol = " "
style = "bold mauve"
format = '[$symbol$version ]($style)'
version_format = "v${major}.${minor}"

[rust]
symbol = " "
style = "bold peach"
format = '[$symbol$version ]($style)'
version_format = "v${major}.${minor}"

# Prompt configurations for cloud providers

[aws]
symbol = " "
style = "bold peach"
disabled = false
force_display = true
format = '[via ](overlay2)[$symbol $profile ]($style)[at ](overlay2)[$region]($style)'

[aws.profile_aliases]
PA90X = 'PA90X'

[aws.region_aliases]
us-east-1      = 'N. Virginia'         # 'us-east-1' 'USE01'      # US East (N. Virginia)
us-east-2      = 'Ohio'                # 'us-east-2' 'USE02'      # US East (Ohio)
us-west-1      = 'N. California'       # 'us-west-1' 'USW01'      # US West (N. California)
us-west-2      = 'Oregon'              # 'us-west-2' 'USW02'      # US West (Oregon)
af-south-1     = 'Cape Town'           # 'af-south-1' 'AFS01'     # Africa (Cape Town)
ap-east-1      = 'Hong Kong'           # 'ap-east-1' 'APE01'      # Asia Pacific (Hong Kong)
ap-south-1     = 'Mumbai'              # 'ap-south-1' 'APS01'     # Asia Pacific (Mumbai)
ap-south-2     = 'Hyderabad'           # 'ap-south-2' 'APS02'     # Asia Pacific (Hyderabad)
ap-northeast-3 = 'Osaka'               # 'ap-northeast-3' 'APNE3' # Asia Pacific (Osaka)
ap-northeast-2 = 'Seoul'               # 'ap-northeast-2' 'APNE2' # Asia Pacific (Seoul)
ap-southeast-1 = 'Singapore'           # 'ap-southeast-1' 'APSE1' # Asia Pacific (Singapore)
ap-southeast-2 = 'Sydney'              # 'ap-southeast-2' 'APSE2' # Asia Pacific (Sydney)
ap-northeast-1 = 'Tokyo'               # 'ap-northeast-1' 'APNE1' # Asia Pacific (Tokyo)
ca-central-1   = 'Central Canada'      # 'ca-central-1' 'CAC01'   # Canada (Central)
cn-north-1     = 'Beijing'             # 'cn-north-1' 'CNN01'     # China (Beijing)
cn-northwest-1 = 'Ningxia'             # 'cn-northwest-1' 'CNNW1' # China (Ningxia)
eu-central-1   = 'Frankfurt'           # 'eu-central-1' 'EUC01'   # Europe (Frankfurt)
eu-west-1      = 'Ireland'             # 'eu-west-1' 'EUW01'      # Europe (Ireland)
eu-west-2      = 'London'              # 'eu-west-2' 'EUW02'      # Europe (London)
eu-south-1     = 'Milan'               # 'eu-south-1' 'EUS01'     # Europe (Milan)
eu-west-3      = 'Paris'               # 'eu-west-3' 'EUW03'      # Europe (Paris)
eu-south-2     = 'Spain'               # 'eu-south-2' 'EUS02'     # Europe (Spain)
eu-north-1     = 'Stockholm'           # 'eu-north-1' 'EUN01'     # Europe (Stockholm)
eu-central-2   = 'Zurich'              # 'eu-central-2' 'EUC02'   # Europe (Zurich)
me-south-1     = 'Bahrain'             # 'me-south-1' 'MES01'     # Middle East (Bahrain)
me-central-1   = 'UAE'                 # 'me-central-1' 'MEC01'   # Middle East (UAE)
sa-east-1      = 'São Paulo'           # 'sa-east-1' 'SAE01'      # South America (São Paulo)

# Custom Color Palette (Based on Catpuccin Mocha)
[palettes.patppuccin]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
