# Starship configurations

# Schema Reference
"$schema" = 'https://starship.rs/config-schema.json'

# Palette Configuration
palette = "catppuccin_mocha"

# Add newline configuration
add_newline = true

# Continuation prompt configuration
continuation_prompt = '[… ](bold mauve)'

# Prompt structure & format configuration
format = """\
$username$hostname \
[on](overlay2) ${env_var.STARSHIP_DISTRO}$shell \
[at](overlay2) $directory \
[$fill]() \
$cmd_duration\
$nodejs$bun$python${custom.py_env}$golang$elixir$rust\
$git_branch$git_status\
$time\
$line_break\
$character\
"""

right_format = """"""

[username]
style_user = "bold mauve"
style_root = "bold mauve"
format = "[ $user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
ssh_symbol = '(SSH)'
style = "bold mauve"
format = '[  $hostname$ssh_symbol]($style)'
trim_at = '.home.patrickambrose.com'
disabled = false

[env_var.STARSHIP_DISTRO]
format = '[$env_value]($style)'
style = "bold pink"
variable = "STARSHIP_DISTRO"
disabled = false

[shell]
format = '[$indicator]($style)'
fish_indicator = 'FISH'
bash_indicator = 'BASH'
powershell_indicator = 'PWSH'
nu_indicator = 'NUSH'
unknown_indicator = 'SH??'
style = 'bold pink'
disabled = false

[directory]
truncation_length = 1
truncation_symbol = " "
style = "bold maroon"
home_symbol = " HOME"
format = "[$path]($style)"

[character]
success_symbol = "[❯](mauve)"
error_symbol = "[❯](red)"

[status]
style = ''
symbol = '[⦿](fg:#f9e2af)'
success_symbol = '[⦿](fg:#a6e3a1)'
not_executable_symbol = '[⦿](fg:#f9e2af)'
not_found_symbol = '[⦿](fg:#f9e2af)'
sigint_symbol = '[⦿](fg:#89dceb)'
signal_symbol = '[⦿](fg:#89b4fa)'
format = '[$symbol]($style)'
map_symbol = true
disabled = false

[fill]
symbol = ' '
style = 'bold overlay2'

[cmd_duration]
min_time = 5000
format = '([took $duration ](bold blue))'

[time]
disabled = false
style = "bold green"
format = '[󱑎 $time]($style)'
time_format = '%R'
utc_time_offset = '+5.5'

# Prompt configuratiuons for git and git-related tools

[git_branch]
symbol = ""
format = "([$symbol $branch]($style))"
truncation_length = 10
truncation_symbol = "…/"
style = "bold peach"

[git_status]
format = '( [\[$all_status\] ]($style))'
style = "bold peach"
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇄"
up_to_date = "✔"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"


# Prompt configuration for programming languages

[python]
symbol = " "
style = "bold sapphire"
version_format = "v${major}.${minor}"
format = '[$symbol$version ]($style)'

[custom.py_env]
detect_files = [ 'pyproject.toml' , 'poetry.lock' ]
detect_folders = [ '.venv' , 'venv' ]
style = "bold sapphire"
format = '[\[$symbol\] ]($style)'
symbol = "󱐋"

[golang]
symbol = " "
style = "bold sapphire"
version_format = "v${major}.${minor}"
format = '[$symbol$version ]($style)'

[nodejs]
symbol = " "
style = "bold sapphire"
format = '[$symbol$version ]($style)'
version_format = "v${major}.${minor}"

[bun]
symbol = "󰳯 "
style = "bold sapphire"
format = '[$symbol$version ]($style)'
version_format = "v${major}.${minor}"

[elixir]
symbol = " "
style = "bold sapphire"
format = '[$symbol$version ]($style)'
version_format = "v${major}.${minor}"

[rust]
symbol = " "
style = "bold sapphire"
format = '[$symbol$version ]($style)'
version_format = "v${major}.${minor}"

# Prompt configurations for cloud providers

[aws]
symbol = " "
style = "bold peach"
disabled = false
force_display = true
format = '[via ](overlay2)[$symbol $profile ]($style)[at ](overlay2)[$region]($style)'

[aws.profile_aliases]
PA90X = 'PA90X'

[aws.region_aliases]
us-east-1      = 'N. Virginia'         # 'us-east-1' 'USE01'      # US East (N. Virginia)
us-east-2      = 'Ohio'                # 'us-east-2' 'USE02'      # US East (Ohio)
us-west-1      = 'N. California'       # 'us-west-1' 'USW01'      # US West (N. California)
us-west-2      = 'Oregon'              # 'us-west-2' 'USW02'      # US West (Oregon)
af-south-1     = 'Cape Town'           # 'af-south-1' 'AFS01'     # Africa (Cape Town)
ap-east-1      = 'Hong Kong'           # 'ap-east-1' 'APE01'      # Asia Pacific (Hong Kong)
ap-south-1     = 'Mumbai'              # 'ap-south-1' 'APS01'     # Asia Pacific (Mumbai)
ap-south-2     = 'Hyderabad'           # 'ap-south-2' 'APS02'     # Asia Pacific (Hyderabad)
ap-northeast-3 = 'Osaka'               # 'ap-northeast-3' 'APNE3' # Asia Pacific (Osaka)
ap-northeast-2 = 'Seoul'               # 'ap-northeast-2' 'APNE2' # Asia Pacific (Seoul)
ap-southeast-1 = 'Singapore'           # 'ap-southeast-1' 'APSE1' # Asia Pacific (Singapore)
ap-southeast-2 = 'Sydney'              # 'ap-southeast-2' 'APSE2' # Asia Pacific (Sydney)
ap-northeast-1 = 'Tokyo'               # 'ap-northeast-1' 'APNE1' # Asia Pacific (Tokyo)
ca-central-1   = 'Central Canada'      # 'ca-central-1' 'CAC01'   # Canada (Central)
cn-north-1     = 'Beijing'             # 'cn-north-1' 'CNN01'     # China (Beijing)
cn-northwest-1 = 'Ningxia'             # 'cn-northwest-1' 'CNNW1' # China (Ningxia)
eu-central-1   = 'Frankfurt'           # 'eu-central-1' 'EUC01'   # Europe (Frankfurt)
eu-west-1      = 'Ireland'             # 'eu-west-1' 'EUW01'      # Europe (Ireland)
eu-west-2      = 'London'              # 'eu-west-2' 'EUW02'      # Europe (London)
eu-south-1     = 'Milan'               # 'eu-south-1' 'EUS01'     # Europe (Milan)
eu-west-3      = 'Paris'               # 'eu-west-3' 'EUW03'      # Europe (Paris)
eu-south-2     = 'Spain'               # 'eu-south-2' 'EUS02'     # Europe (Spain)
eu-north-1     = 'Stockholm'           # 'eu-north-1' 'EUN01'     # Europe (Stockholm)
eu-central-2   = 'Zurich'              # 'eu-central-2' 'EUC02'   # Europe (Zurich)
me-south-1     = 'Bahrain'             # 'me-south-1' 'MES01'     # Middle East (Bahrain)
me-central-1   = 'UAE'                 # 'me-central-1' 'MEC01'   # Middle East (UAE)
sa-east-1      = 'São Paulo'           # 'sa-east-1' 'SAE01'      # South America (São Paulo)

# Custom color palette configurations

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
